# API 1 - Pessoa (Principal)
spring.application.name=api1-pessoa
server.port=8080

# Datasource - MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/api1_pessoa?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Logging
logging.level.com.example.api1pessoa=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.amqp=INFO
